### PR TITLE
Pin all dependency versions in package.json

### LINKED ISSUE #97: Incompatible with typescript ^2.2.x
We are affected by [this issue](https://github.com/Microsoft/TypeScript/issues/13709). At least for now, we need to pin the version of typescript we are using to something in the 2.1 series.

### PR DESCRIPTION
**Pull request by zthomae**
We need to run Typescript 2.1.x for now, because breaking changes in the 2.2 series cause our generated client sources to no longer be usable directly in the browser. In particular, I also pinned the version of @types/lodash to one compatible with this version. Most of the packages have been upgraded as well to what the old rules will install as of this commit.

This fixes #97 with extreme prejudice -- we gain (some) reproducibility at the expense of having to update dependencies manually.

### CODE REVIEW

**Comment by LOZORD** [comment]
Is this a temporary fix or permanent hack?
WRT david-ignoring:
- why is @types/lodash incompatible?
- why is tslint incompatible? (I assume it is related to the problem with upgrading TS.)

**Comment by zthomae** [comment]
I believe that the dependency versions should stay pinned in the interests of giving the game a better chance of continuing to work without maintenance. I think the downsides of this are lessened even more by david -- at least during development we will be alerted when upgrades need to be considered.

As for the other dependencies that are held back:

- Upgrading tslint will cause _many_ lint errors. I think these can be automatically fixed, but I would prefer to do that in a separate commit. And most of the rules are sensible, so I would prefer to fix them than disable them.
- Newer versions of @types/lodash require newer versions of the typescript compiler to work.

**Comment by LOZORD** [comment]
Fine with me; thanks for the explanation.

**Comment by LOZORD** [comment]
Can you please pin/david-ignore `@types/winston`? The build is currently broken :expressionless: 
Also, can you update/fix your other PRs as well please?

**Comment by zthomae** [comment]
I can do that tonight.

**Comment by LOZORD** [comment]
Sure, thanks!

**Pull request merged**
