### PR TITLE
Fix client.js inclusion

### PR DESCRIPTION
**Pull request by zthomae**
I put the static files (`client.html` and `client.js`) in a `client/` directory that is now served by `server.js`. To make the server shorter, I also renamed `client.html` to `index.html`.

### CODE REVIEW

**Comment by Ricky54326** [comment]
aheh

**Comment by LOZORD** [comment]
This is not exactly what I was looking for, as the `client.js` script is not getting run.

**Comment by zthomae** [comment]
I guess I can fix that too :ok_hand:

**Comment by LOZORD** [comment]
Was this the fix? It LGTM :+1:

**Comment by zthomae** [comment]
There are two parts to the fix.

The first is that `client.js` wasn't getting served properly by the server. It was set up to serve the html file, but not the javascript. I changed it to serve an entire directory (a client subdirectory, so you wouldn't have to worry about server things being served as well). You could've added another rule like before just to serve `client.js`, but I think this is probably better.

That makes the client-side javascript loadable. The other problem was that the malformed `</script>` tag made the script not run, even though the browser requested it (you could see that the requests stopped failing in the console). I guess this is one of those edge cases where a browser can request a file even if doesn't actually use it.

I probably could've fixed both of these things at once, but I was racing to get my internet cookies from you :100: :ok_hand: :cookie:

**Comment by LOZORD** [comment]
Ah, thank you. :cookie: and :cake: for that!

**Pull request merged**
