### PR TITLE
Add `david` and update dependencies #77

### PR DESCRIPTION
**Pull request by Oishikatta**
Hi,

I tried this but I wasn't able to get it to build after because of https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#function-declarations-not-allowed-in-blocks-in-strict-mode

With one additional change it got to the tests (but I'm not sure if this change is correct):

``` ---
 src/context/game.ts | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/src/context/game.ts b/src/context/game.ts
index 0a8e533..c356d31 100644
--- a/src/context/game.ts
+++ b/src/context/game.ts
@@ -160,13 +160,13 @@ export default class Game extends Context<Player.GamePlayer> {
   getSortedActions(): Actions.Action[] {
     if (this.isReadyForUpdate()) {

-      function getAgility(action: Actions.Action): number {
+      const getAgility = function getAgility(action: Actions.Action): number {
         return action.actor.stats.agility;
-      }
+      };

-      function getTimestamp(action: Actions.Action): number {
+      const getTimestamp = function getTimestamp(action: Actions.Action): number {
         return action.timestamp;
-      }
+      };

       const playerActions = this.players.map(player => player.character.nextAction);

--
```

But then the tests gave this result:

```
  148 passing (769ms)
  15 pending
  1 failing

  1) Client updateDetails Gold should appear in the view:
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at dist/client/clientSpec.js:342:21
      at tryCatch (node_modules/es6-promise/dist/es6-promise.js:410:12)
      at invokeCallback (node_modules/es6-promise/dist/es6-promise.js:425:13)
      at node_modules/es6-promise/dist/es6-promise.js:172:16
      at flush (node_modules/es6-promise/dist/es6-promise.js:121:5)
```

I saw though that you already have a PR open with several changes for Typescript 2.0, so I thought it might just need those changes also to test right.

### CODE REVIEW

**Comment by LOZORD** [comment]
Please let me know if you're still having issues after rebasing, etc.

**Comment by Oishikatta** [comment]
It wasn't compiling even after a hard reset to a commit before I'd made any changes, but after removing that entire directory and re-cloning I'm able to again.

The first set of errors was resolved by the rebase, but I'm still getting stuck on this one:

```
  1) Client updateDetails Gold should appear in the view:
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at dist/client/clientSpec.js:334:21
      at tryCatch (node_modules/es6-promise/dist/es6-promise.js:410:12)
      at invokeCallback (node_modules/es6-promise/dist/es6-promise.js:425:13)
      at node_modules/es6-promise/dist/es6-promise.js:172:16
      at flush (node_modules/es6-promise/dist/es6-promise.js:121:5)
```

**Comment by LOZORD** [comment]
Yeah, after some searching, I guess [it is bad](https://github.com/mochajs/mocha/issues/2407) to take a `done` callback **and** return a promise.
That is what I wrote [here](https://github.com/LOZORD/xanadu/blob/master/src/client/clientSpec.ts#L370) so that makes sense 😅 

Please change that and any other instances of that antipattern if you have problems testing.

**Review by LOZORD — APPROVED** [review]
Thanks for your work on this! I will merge this once we get AppVeyor running correctly ( #73 ).

**Comment by LOZORD** [comment]
Thanks for your help @Oishikatta! Also, this should fix the warnings that @katamaritaco mentioned a while back. Closes #77.

**Pull request merged**
