### PR TITLE
Add Codacy badge

### PR DESCRIPTION
**Pull request by ankitjain28may**
Please make sure you've followed the guidelines in `CONTRIBUTING.md` when
submitting this pull request!

### CODE REVIEW

**Comment by LOZORD** [comment]
Thanks @ankitjain28may! Do I need to sign up for this, or should it "just work"?

**Comment by ankitjain28may** [comment]
You need to sign up for this thn it will work !

**Comment by LOZORD** [comment]
Awesome, will do 👍

**Comment by LOZORD** [comment]
Thanks, Codacy looks pretty cool.

Would you be interested in [setting up coverage statistics](https://github.com/codacy/node-codacy-coverage#installation) for this project? Otherwise, I can merge this and someone can do it later.

**Comment by ankitjain28may** [comment]
I am  interested but now it takes time.. You can merge this.... And if someone is interested than he is welcomed to do this..!

**Pull request merged**
